//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package agency.highlysuspect.redmill.oldschool.cpw.mods.fml.common;

import agency.highlysuspect.redmill.svc.ModContainerExt;
import com.google.common.base.Joiner;
import com.google.common.collect.Lists;

import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;

public class ModMetadata {
	public String modId;
	public String name;
	public String description;
	public String url = "";
	public String updateUrl = "";
	public String logoFile = "";
	public String version = "";
	public List authorList = Lists.newArrayList();
	public String credits = "";
	public String parent = "";
	public String[] screenshots;
	public ModContainer parentMod;
	public List childMods = Lists.newArrayList();
	public boolean useDependencyInformation;
	public Set requiredMods;
	public List dependencies;
	public List dependants;
	public boolean autogenerated;
	
	public ModMetadata(ModContainerExt ext) {
		this.modId = ext.oldModid;
		this.name = ext.modernModInfo.getDisplayName();
		this.description = ext.modernModInfo.getDescription();
		this.url = ext.modernModInfo.getModURL().map(URL::toString).orElse("");
		//updateUrl
		//logoFile
		this.version = ext.modernModInfo.getVersion().toString();
		//authorList
		//credits
		//parent
		this.screenshots = new String[0];
		this.parentMod = null;
		//childMods
		this.useDependencyInformation = false;
		this.requiredMods = new HashSet();
		this.dependencies = new ArrayList();
		this.dependants = new ArrayList();
		this.autogenerated = false;
	}
	
//	public ModMetadata(JsonNode var1) {
//		Map var2 = Maps.transformValues(var1.getFields(), new ModMetadata$JsonStringConverter((ModMetadata$1)null));
//		this.modId = (String)var2.get(JsonNodeBuilders.aStringBuilder("modid"));
//		if (Strings.isNullOrEmpty(this.modId)) {
//			FMLLog.log(Level.SEVERE, "Found an invalid mod metadata file - missing modid", new Object[0]);
//			throw new LoaderException();
//		} else {
//			this.name = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("name")));
//			this.description = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("description")));
//			this.url = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("url")));
//			this.updateUrl = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("updateUrl")));
//			this.logoFile = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("logoFile")));
//			this.version = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("version")));
//			this.credits = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("credits")));
//			this.parent = Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("parent")));
//			this.authorList = (List)Objects.firstNonNull((List)var2.get(JsonNodeBuilders.aStringBuilder("authors")), Objects.firstNonNull((List)var2.get(JsonNodeBuilders.aStringBuilder("authorList")), this.authorList));
//			this.requiredMods = (Set)this.processReferences(var2.get(JsonNodeBuilders.aStringBuilder("requiredMods")), HashSet.class);
//			this.dependencies = (List)this.processReferences(var2.get(JsonNodeBuilders.aStringBuilder("dependencies")), ArrayList.class);
//			this.dependants = (List)this.processReferences(var2.get(JsonNodeBuilders.aStringBuilder("dependants")), ArrayList.class);
//			this.useDependencyInformation = Boolean.parseBoolean(Strings.nullToEmpty((String)var2.get(JsonNodeBuilders.aStringBuilder("useDependencyInformation"))));
//		}
//	}
	
	public ModMetadata() {
	}
	
//	private Collection processReferences(Object var1, Class var2) {
//		Collection var3 = null;
//
//		try {
//			var3 = (Collection)var2.newInstance();
//		} catch (Exception var6) {
//		}
//
//		if (var1 == null) {
//			return var3;
//		} else {
//			Iterator var4 = ((List)var1).iterator();
//
//			while(var4.hasNext()) {
//				String var5 = (String)var4.next();
//				var3.add(VersionParser.parseVersionReference(var5));
//			}
//
//			return var3;
//		}
//	}
	
	public String getChildModCountString() {
		return String.format("%d child mod%s", this.get_childMods().size(), this.get_childMods().size() != 1 ? "s" : "");
	}
	
	public String getAuthorList() {
		return Joiner.on(", ").join(this.get_authorList());
	}
	
	public String getChildModList() {
		//return Joiner.on(", ").join(Lists.transform(this.get_childMods(), new ModNameFunction()));
		return "";
	}
	
	public String printableSortingRules() {
		return "";
	}
	
	public String get_modId() {
		return this.modId;
	}
	
	public void set_modId(String var1) {
		this.modId = var1;
	}
	
	public String get_name() {
		return this.name;
	}
	
	public void set_name(String var1) {
		this.name = var1;
	}
	
	public String get_description() {
		return this.description;
	}
	
	public void set_description(String var1) {
		this.description = var1;
	}
	
	public String get_url() {
		return this.url;
	}
	
	public void set_url(String var1) {
		this.url = var1;
	}
	
	public String get_updateUrl() {
		return this.updateUrl;
	}
	
	public void set_updateUrl(String var1) {
		this.updateUrl = var1;
	}
	
	public String get_logoFile() {
		return this.logoFile;
	}
	
	public void set_logoFile(String var1) {
		this.logoFile = var1;
	}
	
	public String get_version() {
		return this.version;
	}
	
	public void set_version(String var1) {
		this.version = var1;
	}
	
	public List get_authorList() {
		return this.authorList;
	}
	
	public void set_authorList(List var1) {
		this.authorList = var1;
	}
	
	public String get_credits() {
		return this.credits;
	}
	
	public void set_credits(String var1) {
		this.credits = var1;
	}
	
	public String get_parent() {
		return this.parent;
	}
	
	public void set_parent(String var1) {
		this.parent = var1;
	}
	
	public String[] get_screenshots() {
		return this.screenshots;
	}
	
	public void set_screenshots(String[] var1) {
		this.screenshots = var1;
	}
	
	public ModContainer get_parentMod() {
		return this.parentMod;
	}
	
	public void set_parentMod(ModContainer var1) {
		this.parentMod = var1;
	}
	
	public List get_childMods() {
		return this.childMods;
	}
	
	public void set_childMods(List var1) {
		this.childMods = var1;
	}
	
	public boolean get_useDependencyInformation() {
		return this.useDependencyInformation;
	}
	
	public void set_useDependencyInformation(boolean var1) {
		this.useDependencyInformation = var1;
	}
	
	public Set get_requiredMods() {
		return this.requiredMods;
	}
	
	public void set_requiredMods(Set var1) {
		this.requiredMods = var1;
	}
	
	public List get_dependencies() {
		return this.dependencies;
	}
	
	public void set_dependencies(List var1) {
		this.dependencies = var1;
	}
	
	public List get_dependants() {
		return this.dependants;
	}
	
	public void set_dependants(List var1) {
		this.dependants = var1;
	}
	
	public boolean get_autogenerated() {
		return this.autogenerated;
	}
	
	public void set_autogenerated(boolean var1) {
		this.autogenerated = var1;
	}
}
